// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pdfutil} from '../models';

export function GetCurrentFile():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<Array<pdfutil.Form>>;
