// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPdfForm() {
  return window['go']['main']['App']['GetPdfForm']();
}

export function GetPreviewContent() {
  return window['go']['main']['App']['GetPreviewContent']();
}

export function GetPreviewFilePath() {
  return window['go']['main']['App']['GetPreviewFilePath']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function UpdatePdfForm(arg1) {
  return window['go']['main']['App']['UpdatePdfForm'](arg1);
}

export function UpdatePdfFormWithFieldNames() {
  return window['go']['main']['App']['UpdatePdfFormWithFieldNames']();
}
