// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pdfutil} from '../models';

export function GetPdfForm():Promise<pdfutil.Form>;

export function GetPreviewContent():Promise<string>;

export function GetPreviewFilePath():Promise<string>;

export function OpenFileDialog():Promise<void>;

export function UpdatePdfForm(arg1:pdfutil.Form):Promise<void>;

export function UpdatePdfFormWithFieldNames():Promise<void>;
